// APARTMENT RADAR — מאגר דירות
// מתעדכן אוטומטית פעמיים ביום (09:30 / 19:30) ע"י daily-apartment-search-center
// כלל: רק דירות עם מחיר מפורסם. דירה בלי מחיר לא נכנסת למאגר.
// מפתח הזהות של דירה = מזהה המודעה בסוף ה-URL. לפניו בודקים כפילות, לא לפי כתובת.
// לא נכנסות: יחידות דיור עד 35 מ"ר, קבוצות רכישה/זכות לנכס, ומחיר מעל התקרה.

window.APARTMENT_DATA = {
  updatedAt: "2026-09-30T22:21:00+03:00",
  budget: 1600000,
  equity: 350000,
  leverage: 0.75,
  deadline: "2026-07-31",
  removed: [
    "f2530t31",
    "dmdvrzgj",
    "19qk1852",
    "XB74Y288Jex",
    "obS0EwM67UP",
    "0HwCnLjFZjx",
    "ddl7okai",
    "ovje5j8f",
    "px3b0bwz",
    "2T9KhvoA1QD",
    "IPzsO9sBneR",
    "o8v2coo7",
    "j2QFCcpN7lK",
    "ipSCibAop2j",
    "vsmvtvii",
    "goxgu9n3",
    "ee15laj0",
    "4wuqbw6e",
    "7w7iej8q",
    "44c3UrEMARX",
    "dyoyukVTp6P",
    "isdgw5tx",
    "3mn3da3h",
    "5nipn47i",
    "lv4q3gi2",
    "r5wk0vfv",
    "bkdun8zl",
    "77gehdl8",
    "SpO98umj7A3"
  ],
  apartments: [
    {
      id: "reh-mdln-traves",
      address: "אחים טרבס, רחובות",
      city: "רחובות",
      neighborhood: "מרכז העיר",
      price: 1790000,
      rooms: 4,
      sqm: 88,
      floor: 1,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/vzqaYIKQWCG",
      firstSeen: "2026-09-29"
    },
    {
      id: "reh-mdln-hahalutz-7",
      address: "החלוץ 7, רחובות",
      city: "רחובות",
      neighborhood: "מרכז העיר",
      price: 1790000,
      rooms: 3,
      sqm: 75,
      floor: 2,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/l0OK3tD78QQ",
      firstSeen: "2026-09-29"
    },
    {
      id: "reh-mdln-ben-gurion-30",
      address: "בן גוריון 30, רחובות",
      city: "רחובות",
      neighborhood: "אבן גבירול",
      price: 1780000,
      rooms: 3,
      sqm: 77,
      floor: 4,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/AoJG9rc5Q88",
      firstSeen: "2026-09-29"
    },
    {
      id: "reh-mdln-dolinski",
      address: "אהוד דולינסקי, רחובות",
      city: "רחובות",
      neighborhood: "אושיות",
      price: 1590000,
      rooms: 3,
      sqm: 74,
      floor: 1,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/l2lJpXcWDNU",
      firstSeen: "2026-09-29"
    },
    {
      id: "reh-mdln-ehad-haam",
      address: "אחד העם, רחובות",
      city: "רחובות",
      neighborhood: "מרכז העיר",
      price: 1730000,
      rooms: 3,
      sqm: 78,
      floor: 7,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/HITc8bcgr6J",
      firstSeen: "2026-09-29"
    },
    {
      id: "reh-mdln-trumpeldor-5",
      address: "טרומפלדור 5, רחובות",
      city: "רחובות",
      neighborhood: "אושיות",
      price: 1550000,
      rooms: 3,
      sqm: 62,
      floor: 2,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/yViECGyxBUI",
      firstSeen: "2026-09-29"
    },
    {
      id: "reh-mdln-taran-19",
      address: "תר\"ן 19, רחובות",
      city: "רחובות",
      neighborhood: "צפון מזרח",
      price: 1635000,
      rooms: 2.5,
      sqm: 60,
      floor: 4,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/UNbpBSG0D25",
      firstSeen: "2026-09-29"
    },
    {
      id: "reh-mdln-bnei-moshe-13",
      address: "בני משה 13, רחובות",
      city: "רחובות",
      neighborhood: "מרכז העיר",
      price: 1700000,
      rooms: 3,
      sqm: 75,
      floor: 2,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/rcwwnlJsiK2",
      firstSeen: "2026-09-29"
    },
    {
      id: "reh-mdln-arlozorov",
      address: "ארלוזורוב, רחובות",
      city: "רחובות",
      neighborhood: "מרכז העיר",
      price: 1550000,
      rooms: 3,
      sqm: 75,
      floor: 4,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/4G1XIRZY8MH",
      firstSeen: "2026-09-29"
    },
    {
      id: "holon-mdln-arava-6",
      address: "ערבה 6, חולון",
      city: "חולון",
      neighborhood: "ג'סי כהן",
      price: 1720000,
      rooms: 3,
      sqm: 76,
      floor: 0,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/A8z9IO59x2N",
      firstSeen: "2026-09-29"
    },
    {
      id: "holon-mdln-homa-umigdal",
      address: "חומה ומגדל, חולון",
      city: "חולון",
      neighborhood: "קרית עבודה",
      price: 1790000,
      rooms: 3,
      sqm: 70,
      floor: 4,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/ADETWXIOXpe",
      firstSeen: "2026-09-29"
    },
    {
      id: "holon-mdln-yavnieli",
      address: "יבניאלי, חולון",
      city: "חולון",
      neighborhood: "נאות רחל",
      price: 1690000,
      rooms: 2.5,
      sqm: 65,
      floor: 3,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/5y7ODYEawps",
      firstSeen: "2026-09-29"
    },
    {
      id: "holon-mdln-tzeelim-26",
      address: "צאלים 26, חולון",
      city: "חולון",
      neighborhood: "נאות רחל",
      price: 1795000,
      rooms: 3,
      sqm: 80,
      floor: 4,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/dOcJa9iUR4c",
      firstSeen: "2026-09-29",
      tags: ["ירד 55K"]
    },
    {
      id: "holon-mdln-hasdai",
      address: "חסדאי, חולון",
      city: "חולון",
      neighborhood: "גרין ועם",
      price: 1690000,
      rooms: 3,
      sqm: 65,
      floor: 3,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/LwLIGJRmRDJ",
      firstSeen: "2026-09-29"
    },
    {
      id: "holon-mdln-kapah-17",
      address: "קפאח 17, חולון",
      city: "חולון",
      neighborhood: "גרין ועם",
      price: 1610000,
      rooms: 3,
      sqm: 67,
      floor: 4,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/uyEh3hTJbwx",
      firstSeen: "2026-09-29"
    },
    {
      id: "by-mdln-danin-31",
      address: "דנין 31, בת ים",
      city: "בת ים",
      neighborhood: "מרכז העיר",
      price: 1690000,
      rooms: 2.5,
      sqm: 70,
      floor: 1,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/ZiIeSLcJUJG",
      firstSeen: "2026-09-29"
    },
    {
      id: "by-mdln-bar-ilan-44",
      address: "בר אילן 44, בת ים",
      city: "בת ים",
      neighborhood: "דרום מערב",
      price: 1690000,
      rooms: 3.5,
      sqm: 80,
      floor: 3,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/RTs2vyDUQXn",
      firstSeen: "2026-09-29"
    },
    {
      id: "by-mdln-shikma-8",
      address: "שקמה 8, בת ים",
      city: "בת ים",
      neighborhood: "דרום מערב",
      price: 1740000,
      rooms: 3,
      sqm: 75,
      floor: 2,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/k6rQYSxwVtr",
      firstSeen: "2026-09-29"
    },
    {
      id: "by-mdln-yoseftal-45",
      address: "יוספטל 45, בת ים",
      city: "בת ים",
      neighborhood: "מרכז העיר",
      price: 1690000,
      rooms: 3.5,
      sqm: 71,
      floor: 5,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/MzP4YCGc9Li",
      firstSeen: "2026-09-29"
    },
    {
      id: "by-mdln-rachel-1",
      address: "רחל המשוררת 1, בת ים",
      city: "בת ים",
      neighborhood: "דרום מערב",
      price: 1600000,
      rooms: 2.5,
      sqm: 73,
      floor: 2,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/jGQRRPk55MJ",
      firstSeen: "2026-09-29"
    },
    {
      id: "by-mdln-halutzim-16",
      address: "החלוצים 16, בת ים",
      city: "בת ים",
      neighborhood: "עמידר",
      price: 1790000,
      rooms: 3,
      sqm: 71,
      floor: 4,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/QbtG9AziDM3",
      firstSeen: "2026-09-29"
    },
    {
      id: "rlz-mdln-dror-19",
      address: "דרור 19, ראשון לציון",
      city: "ראשון לציון",
      neighborhood: "רמב\"ם",
      price: 1780000,
      rooms: 3,
      sqm: 77,
      floor: 4,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/GtbEV7UA85D",
      firstSeen: "2026-09-29",
      tags: ["חדש"]
    },
    {
      id: "rlz-mdln-yehuda-16",
      address: "יהודה 16, ראשון לציון",
      city: "ראשון לציון",
      neighborhood: "רמב\"ם",
      price: 1680000,
      rooms: 3,
      sqm: 60,
      floor: 2,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/WCE7PulOYwa",
      firstSeen: "2026-09-29"
    },
    {
      id: "rlz-mdln-kiryat-sefer-28",
      address: "קרית ספר 28, ראשון לציון",
      city: "ראשון לציון",
      neighborhood: "כצנלסון",
      price: 1590000,
      rooms: 3.5,
      sqm: 75,
      floor: 2,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/gSmv3OxSD1B",
      firstSeen: "2026-09-29"
    },
    {
      id: "rlz-mdln-karl-netter-22",
      address: "קרל נטר 22, ראשון לציון",
      city: "ראשון לציון",
      neighborhood: "אברמוביץ",
      price: 1650000,
      rooms: 3,
      sqm: 67,
      floor: 3,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/37RWNeQHEIn",
      firstSeen: "2026-09-29"
    },
    {
      id: "rlz-mdln-rashi-rambam",
      address: "רש\"י, ראשון לציון",
      city: "ראשון לציון",
      neighborhood: "רמב\"ם",
      price: 1750000,
      rooms: 3,
      sqm: 70,
      floor: 1,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/uHF0lvpzsML",
      firstSeen: "2026-09-29"
    },
    {
      id: "rlz-mdln-pinsker-25",
      address: "פינסקר 25, ראשון לציון",
      city: "ראשון לציון",
      neighborhood: "נחלת יהודה",
      price: 1590000,
      rooms: 3,
      sqm: 57,
      floor: 2,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/akNFNpU9gnA",
      firstSeen: "2026-09-29",
      tags: ["ירד 100K"]
    },
    {
      id: "rlz-mdln-keren-kayemet-15",
      address: "קרן קימת 15, ראשון לציון",
      city: "ראשון לציון",
      neighborhood: "אברמוביץ",
      price: 1590000,
      rooms: 2,
      sqm: 55,
      floor: 1,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/TyfKoU6hiH7",
      firstSeen: "2026-09-29"
    },
    {
      id: "rlz-mdln-noruk-re",
      address: "נורוק, ראשון לציון",
      city: "ראשון לציון",
      neighborhood: "רמת אליהו",
      price: 1790000,
      rooms: 2,
      sqm: 45,
      floor: 3,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/nyEIo5Ng9hn",
      firstSeen: "2026-09-29"
    },
    {
      id: "rlz-mdln-naftali-halel",
      address: "נפתלי הלל, ראשון לציון",
      city: "ראשון לציון",
      neighborhood: "אברמוביץ",
      price: 1790000,
      rooms: 3,
      sqm: 70,
      floor: 3,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/U1lcF5bJ007",
      firstSeen: "2026-09-29"
    },
    {
      id: "rlz-y2-rozental-9",
      address: "חיה רוזנטל-חביליו 9, ראשון לציון",
      city: "ראשון לציון",
      neighborhood: "נוריות",
      price: 1500000,
      rooms: 3,
      sqm: 93,
      floor: 13,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/center-and-sharon/pw8dni7u",
      renewal: "none",
      tags: [
        "קומה גבוהה"
      ],
      firstSeen: "2026-08-31"
    },
    {
      id: "rlz-y2-ramat-eliahu-45",
      address: "רמת אליהו, ראשון לציון",
      city: "ראשון לציון",
      neighborhood: "רמת אליהו",
      price: 1390000,
      rooms: 2.5,
      sqm: 45,
      floor: 2,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/center-and-sharon/4v5zzk2l",
      renewal: "none",
      tags: [],
      firstSeen: "2026-08-31"
    },
    {
      id: "rlz-y2-betzalel-9",
      address: "סמטת בצלאל 9, ראשון לציון",
      city: "ראשון לציון",
      neighborhood: "רמב\"ם",
      price: 1590000,
      rooms: 3,
      sqm: 81,
      floor: 4,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/center-and-sharon/cp9kdiu3",
      renewal: "none",
      tags: [
        "ירד 200K"
      ],
      firstSeen: "2026-08-31"
    },
    {
      id: "rlz-mdln-olei-hagardom",
      address: "עולי הגרדום, ראשון לציון",
      city: "ראשון לציון",
      neighborhood: "רמז",
      price: 1450000,
      rooms: 2,
      sqm: 50,
      floor: 1,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/center-and-sharon/iar6p1ig",
      renewal: "none",
      tags: [
        "ירד ב-40,000 ₪"
      ],
      firstSeen: "2026-08-31",
      note: "גם במדלן: QzyCiWjLMQL באותו מחיר"
    },
    {
      id: "rlz-mdln-shalom-ash-26",
      address: "שלום אש 26, ראשון לציון",
      city: "ראשון לציון",
      neighborhood: "רמת אליהו",
      price: 1500000,
      rooms: 3,
      sqm: 58,
      floor: 2,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/center-and-sharon/myhr7kfq",
      renewal: "none",
      tags: [],
      firstSeen: "2026-08-31"
    },
    {
      id: "rlz-mdln-asher-levin-3",
      address: "אשר לוין 3, ראשון לציון",
      city: "ראשון לציון",
      neighborhood: "רמב\"ם",
      price: 1560000,
      rooms: 3,
      sqm: 90,
      floor: 3,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/lJz4dOcSxqA",
      renewal: "none",
      tags: [],
      firstSeen: "2026-08-31"
    },
    {
      id: "rlz-mdln-agnon-re",
      address: "עגנון, ראשון לציון",
      city: "ראשון לציון",
      neighborhood: "רמת אליהו",
      price: 1590000,
      rooms: 3,
      sqm: 39,
      floor: 0,
      source: "מדלן",
      url: null,
      renewal: "none",
      tags: [
        "קומת קרקע"
      ],
      firstSeen: "2026-08-31"
    },
    {
      id: "rlz-mdln-marganit-kr",
      address: "המרגנית, ראשון לציון",
      city: "ראשון לציון",
      neighborhood: "קרית ראשון",
      price: 1600000,
      rooms: 3,
      sqm: 68,
      floor: 1,
      source: "מדלן",
      url: null,
      renewal: "none",
      tags: [],
      firstSeen: "2026-08-31"
    },
    {
      id: "rg-xpwl1yi4",
      address: "שדרות הרב לוין 16",
      city: "רמת גן",
      neighborhood: "רמת עמידר",
      price: 1200000,
      rooms: 3,
      sqm: 76,
      floor: 1,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/tel-aviv-area/xpwl1yi4",
      renewal: "potential",
      renewalNote: "רמת עמידר — שכונת התחדשות עירונית מובילה בר״ג, פרויקטים בשלבי תכנון.",
      tags: [
        "חניה",
        "בהזדמנות"
      ],
      hot: true,
      firstSeen: "2026-09-01"
    },
    {
      id: "holon-gk2y2a8q",
      address: "הגאונים",
      city: "חולון",
      neighborhood: "ג'סי כהן",
      price: 1350000,
      rooms: 2,
      sqm: 45,
      floor: 4,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/tel-aviv-area/gk2y2a8q",
      renewal: "none",
      tags: [
        "ירד ב-75,000 ₪"
      ],
      firstSeen: "2026-09-01"
    },
    {
      id: "holon-svj9wujh",
      address: "יוטבתה",
      city: "חולון",
      neighborhood: "ג'סי כהן",
      price: 1400000,
      rooms: 2,
      sqm: 45,
      floor: 2,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/tel-aviv-area/svj9wujh",
      renewal: "none",
      tags: [],
      firstSeen: "2026-09-01"
    },
    {
      id: "by-bv8b23w1",
      address: "רוטשילד",
      city: "בת ים",
      neighborhood: "עמידר",
      price: 1390000,
      rooms: 2,
      sqm: 65,
      floor: 4,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/tel-aviv-area/bv8b23w1",
      renewal: "potential",
      renewalNote: "עמידר/רוטשילד בת ים — מתחם התחדשות עירונית פעיל.",
      tags: [
        "בהזדמנות"
      ],
      hot: true,
      firstSeen: "2026-09-01"
    },
    {
      id: "by-igczouh5",
      address: "דרך בן גוריון 138",
      city: "בת ים",
      neighborhood: "דרום חדש / פארק הים",
      price: 1250000,
      rooms: 2,
      sqm: null,
      floor: null,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/tel-aviv-area/igczouh5",
      renewal: "none",
      tags: [
        "נוף לים"
      ],
      firstSeen: "2026-09-01"
    },
    {
      id: "by-3qfbazxv",
      address: "החשמונאים 46",
      city: "בת ים",
      neighborhood: "לב העיר",
      price: 1425000,
      rooms: 2.5,
      sqm: null,
      floor: 4,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/tel-aviv-area/3qfbazxv",
      renewal: "none",
      tags: [
        "בלעדי"
      ],
      firstSeen: "2026-09-01"
    },
    {
      id: "by-3n31l5ki",
      address: "אלי כהן 6",
      city: "בת ים",
      neighborhood: "רמת הנשיא",
      price: 1499999,
      rooms: 2.5,
      sqm: 65,
      floor: 1,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/tel-aviv-area/3n31l5ki",
      renewal: "none",
      tags: [
        "עלה ב-50,000 ₪"
      ],
      firstSeen: "2026-09-01"
    },
    {
      id: "by-qsonmq6b",
      address: "שדרות בר אילן",
      city: "בת ים",
      neighborhood: "דרום מערב ותיק",
      price: 1450000,
      rooms: 2.5,
      sqm: 57,
      floor: 4,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/tel-aviv-area/qsonmq6b",
      renewal: "none",
      tags: [],
      firstSeen: "2026-09-01"
    },
    {
      id: "pt-5cn6m1vy",
      address: "אחדות",
      city: "פתח תקווה",
      neighborhood: "אחדות",
      price: 1390000,
      rooms: 2,
      sqm: 46,
      floor: 3,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/center-and-sharon/5cn6m1vy",
      renewal: "none",
      tags: [],
      firstSeen: "2026-09-01"
    },
    {
      id: "rehovot-3wupakqt",
      address: "חיים אליעזר מילצ'ן 7",
      city: "רחובות",
      neighborhood: "מילצ'ן",
      price: 1700000,
      rooms: 3.5,
      sqm: 61,
      floor: 3,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/center-and-sharon/3wupakqt",
      renewal: "verified",
      renewalNote: "רחוב מילצ'ן כולו במתחם פינוי-בינוי מאושר ברחובות.",
      tags: [
        "פינוי-בינוי",
        "חריג תקציב"
      ],
      hot: true,
      firstSeen: "2026-09-01"
    },
    {
      id: "bb-dxy9zwt4",
      address: "הרב דנגור 7",
      city: "בני ברק",
      neighborhood: "פרדס כץ",
      price: 1450000,
      rooms: 2,
      sqm: 61,
      floor: 0,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/center-and-sharon/dxy9zwt4",
      renewal: "none",
      tags: [
        "דירת גן",
        "קומת קרקע"
      ],
      firstSeen: "2026-09-01"
    },
    {
      id: "bb-k1la9jde",
      address: "אברהם בן דוד",
      city: "בני ברק",
      neighborhood: "קרית ויז'ניץ",
      price: 1080000,
      rooms: 2.5,
      sqm: null,
      floor: 4,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/center-and-sharon/k1la9jde",
      renewal: "none",
      tags: [
        "מתחת למיליון"
      ],
      firstSeen: "2026-09-01"
    },
    {
      id: "bb-p72dbqyp",
      address: "בורוכוב",
      city: "בני ברק",
      neighborhood: "—",
      price: 1450000,
      rooms: 2.5,
      sqm: 45,
      floor: 0,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/center-and-sharon/p72dbqyp",
      renewal: "none",
      tags: [
        "קומת קרקע"
      ],
      firstSeen: "2026-09-01"
    },
    {
      id: "bb-dvusw5rm",
      address: "רב אמי",
      city: "בני ברק",
      neighborhood: "קרית נדבורנא",
      price: 1420000,
      rooms: 2.5,
      sqm: null,
      floor: 4,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/center-and-sharon/dvusw5rm",
      renewal: "none",
      tags: [],
      firstSeen: "2026-09-01"
    },
    {
      id: "gs-r9ymuyl8",
      address: "דוד בן גוריון 11",
      city: "גבעת שמואל",
      neighborhood: "השכונה הוותיקה",
      price: 1150000,
      rooms: 2,
      sqm: null,
      floor: 7,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/center-and-sharon/r9ymuyl8",
      renewal: "none",
      tags: [
        "ירד ב-50,000 ₪"
      ],
      firstSeen: "2026-09-01"
    },
    {
      id: "gs-mg6r443q",
      address: "דוד בן גוריון",
      city: "גבעת שמואל",
      neighborhood: "—",
      price: 1430000,
      rooms: 2,
      sqm: null,
      floor: 1,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/center-and-sharon/mg6r443q",
      renewal: "none",
      tags: [
        "בלעדי"
      ],
      firstSeen: "2026-09-01"
    },
    {
      id: "gs-ut5ee4no",
      address: "ז'בוטינסקי 50",
      city: "גבעת שמואל",
      neighborhood: "רמת אילן",
      price: 1399000,
      rooms: 2,
      sqm: 42,
      floor: 8,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/center-and-sharon/ut5ee4no",
      renewal: "none",
      tags: [
        "ירד ב-41,000 ₪"
      ],
      firstSeen: "2026-09-01"
    },
    {
      id: "gs-o58uzjys",
      address: "דוד בן גוריון",
      city: "גבעת שמואל",
      neighborhood: "—",
      price: 1350000,
      rooms: 2,
      sqm: 38,
      floor: 4,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/center-and-sharon/o58uzjys",
      renewal: "none",
      tags: [],
      firstSeen: "2026-09-01"
    },
    {
      id: "gs-6czy8ll5",
      address: "ז'בוטינסקי 50",
      city: "גבעת שמואל",
      neighborhood: "רמת אילן",
      price: 1325000,
      rooms: 2,
      sqm: null,
      floor: 11,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/center-and-sharon/6czy8ll5",
      renewal: "none",
      tags: [],
      firstSeen: "2026-09-01"
    },
    {
      id: "gs-iatsrwn6",
      address: "דוד בן גוריון",
      city: "גבעת שמואל",
      neighborhood: "—",
      price: 1365000,
      rooms: 2,
      sqm: null,
      floor: 4,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/center-and-sharon/iatsrwn6",
      renewal: "none",
      tags: [
        "בלעדי"
      ],
      firstSeen: "2026-09-01"
    },
    {
      id: "rg-fb-1750500839594443",
      address: "שיכון ותיקים, רמת גן",
      city: "רמת גן",
      neighborhood: "שיכון ותיקים",
      price: 1020000,
      rooms: 2,
      sqm: null,
      floor: null,
      source: "פייסבוק",
      url: "https://www.facebook.com/marketplace/item/1750500839594443/",
      renewal: "none",
      tags: [
        "מתחת למיליון וחצי"
      ],
      firstSeen: "2026-09-01"
    },
    {
      id: "holon-fb-1039174208987437",
      address: "רחוב חנקין",
      city: "חולון",
      neighborhood: "קרית עבודה",
      price: 1260000,
      rooms: 2,
      sqm: null,
      floor: 2,
      source: "פייסבוק",
      url: "https://www.facebook.com/marketplace/item/1039174208987437/",
      renewal: "potential",
      renewalNote: "המוכר מציין פינוי-בינוי ברחוב חנקין, חולון (סמוך לקרית עבודה).",
      tags: [
        "פינוי-בינוי"
      ],
      hot: true,
      firstSeen: "2026-09-01"
    },
    {
      id: "holon-y2-3wej9tiy",
      address: "הגאונים",
      city: "חולון",
      neighborhood: "ג'סי כהן",
      price: 1395000,
      rooms: 2,
      sqm: 43,
      floor: 7,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/tel-aviv-area/3wej9tiy",
      renewal: "none",
      tags: [
        "בלעדי",
        "ירד ב-35,000 ₪"
      ],
      note: "בלעדי עולם הנדל\"ן. רחוב הגאונים — כמה מודעות באותו אזור בטווח המחיר.",
      firstSeen: "2026-09-01"
    },
    {
      id: "by-y2-nurit-hirsch-5",
      address: "נורית הירש 5",
      city: "בת ים",
      neighborhood: "דרום חדש / פארק הים",
      price: 780000,
      rooms: 3,
      sqm: 90,
      floor: 5,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/tel-aviv-area/h6hxa64e",
      renewal: "none",
      tags: [
        "מחיר חריג"
      ],
      note: "780K ל-3 חד' 90 מ\"ר באזור פארק הים — נמוך משמעותית מהשוק. לבדוק אם זו מכירת חלק בנכס / זכויות / דיירות מוגנת.",
      firstSeen: "2026-09-01"
    },
    {
      id: "by-y2-eli-cohen-6-y2",
      address: "אלי כהן 6",
      city: "בת ים",
      neighborhood: "רמת הנשיא",
      price: 1496999,
      rooms: 2.5,
      sqm: null,
      floor: null,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/tel-aviv-area/if1ud2hn",
      renewal: "none",
      tags: [
        "עלה ב-46,999 ₪",
        "שיא מרכז"
      ],
      note: "אותה כתובת כמו by-mdln-eli-cohen-6 (מדלן) — ככל הנראה אותו נכס, מודעה שנייה.",
      firstSeen: "2026-09-01"
    },
    {
      id: "by-y2-hashmonaim-28",
      address: "החשמונאים 28",
      city: "בת ים",
      neighborhood: "לב העיר",
      price: 1450000,
      rooms: 2.5,
      sqm: null,
      floor: null,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/tel-aviv-area/qiys61uo",
      renewal: "none",
      tags: [
        "ירד ב-70,000 ₪",
        "Home Way"
      ],
      note: "קרוב ל-by-mdln-hashmonaim-46 (מדלן) — ייתכן אותו בניין/נכס.",
      firstSeen: "2026-09-01"
    },
    {
      id: "bb-mdln-trumpeldor-20",
      address: "טרומפלדור 20",
      city: "בני ברק",
      neighborhood: "פרדס כץ ויסודות",
      price: 1250000,
      rooms: 8,
      sqm: 100,
      floor: 1,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/ucRHgDGRRr4",
      renewal: "none",
      tags: [
        "פוטנציאל חלוקה"
      ],
      note: "8 חד' / 100 מ\"ר בק1 ב-1.25M — דירה גדולה ישנה, פוטנציאל לחלוקה ל-2 יח'. פרדס כץ.",
      firstSeen: "2026-09-01"
    },
    {
      id: "holon-mdln-hameorer-3",
      address: "המעורר 3",
      city: "חולון",
      neighborhood: "נאות רחל",
      price: 1190000,
      rooms: 1.5,
      sqm: 35,
      floor: 0,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/WHpkRtRQoVg",
      renewal: "none",
      tags: [
        "קומת קרקע"
      ],
      note: "1.5 חד' קטנה בקומת קרקע — כניסה נמוכה למחיר. תוקן ב-14.9: העיר הייתה מתויגת בטעות \"ראשון לציון\", בפועל חולון (נאות רחל).",
      firstSeen: "2026-09-03"
    },
    {
      id: "holon-mdln-hahistadrut-rasco-b",
      address: "ההסתדרות",
      city: "חולון",
      neighborhood: "רסקו ב'",
      price: 1390000,
      rooms: 2,
      sqm: 42,
      floor: 0,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/E4IxrOlVGVk",
      renewal: "none",
      tags: [
        "קומת קרקע"
      ],
      firstSeen: "2026-09-03"
    },
    {
      id: "bb-4my3wacu",
      address: "רבי עקיבא 36",
      city: "בני ברק",
      neighborhood: "הר שלום",
      price: 1180000,
      rooms: 2,
      sqm: 52,
      floor: 1,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/center-and-sharon/4my3wacu",
      renewal: "none",
      tags: [
        "דירת גן"
      ],
      firstSeen: "2026-09-11"
    },
    {
      id: "by-9daee4ns",
      address: "ירושלים 55",
      city: "בת ים",
      neighborhood: "—",
      price: 1450000,
      rooms: 3,
      sqm: 68,
      floor: 0,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/tel-aviv-area/9daee4ns",
      renewal: "none",
      tags: [
        "ירד ב-80,000 ₪",
        "בהזדמנות"
      ],
      note: "3 חד' 68 מ\"ר בקומת קרקע — מחיר למ\"ר מהטובים בבת ים בטווח הזה.",
      hot: true,
      firstSeen: "2026-09-11"
    },
    {
      id: "by-flcoq1e3",
      address: "הלפר",
      city: "בת ים",
      neighborhood: "—",
      price: 1385000,
      rooms: 2,
      sqm: 49,
      floor: 2,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/tel-aviv-area/flcoq1e3",
      renewal: "none",
      tags: [],
      firstSeen: "2026-09-11"
    },
    {
      id: "by-fb-1366470128202664",
      address: "דניאל",
      city: "בת ים",
      neighborhood: "לב העיר",
      price: 1440000,
      rooms: 2.5,
      sqm: 65,
      floor: null,
      source: "פייסבוק",
      url: "https://www.facebook.com/marketplace/item/1366470128202664/",
      renewal: "none",
      tags: [
        "פייסבוק"
      ],
      note: "2.5 חדרים 65 מ\"ר לפי כרטיס המודעה. ייתכן קרוב ל-by-daniel-lev-hair / by-daniel-57-lev-hair (יד2) — אותו רחוב",
      firstSeen: "2026-09-11"
    },
    {
      id: "rehovot-jyj9cnx2",
      address: "ההגנה",
      city: "רחובות",
      neighborhood: "אבני חן",
      price: 1410000,
      rooms: 2.5,
      sqm: 47,
      floor: 2,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/center-and-sharon/jyj9cnx2",
      renewal: "none",
      tags: [],
      firstSeen: "2026-09-11"
    },
    {
      id: "ramat-gan-6djjcw4y",
      address: "ביאליק",
      city: "רמת גן",
      neighborhood: "שכונת בן גוריון",
      price: 1320000,
      rooms: 3,
      sqm: null,
      floor: 0,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/tel-aviv-area/6djjcw4y",
      renewal: "none",
      tags: [
        "ירד ב-30,000 ₪"
      ],
      firstSeen: "2026-09-11"
    },
    {
      id: "bat-yam-l4t79pyi",
      address: "מתתיהו גנם",
      city: "בת ים",
      neighborhood: "ניצנה",
      price: 1399000,
      rooms: 2,
      sqm: 43,
      floor: 3,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/tel-aviv-area/l4t79pyi",
      renewal: "potential",
      renewalNote: "ניצנה - שכונה חמה לפינוי-בינוי",
      tags: [],
      firstSeen: "2026-09-11"
    },
    {
      id: "bat-yam-fhvn5ll9",
      address: "בלפור",
      city: "בת ים",
      neighborhood: "דרום מערב ותיק",
      price: 1450000,
      rooms: 2.5,
      sqm: 67,
      floor: 3,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/tel-aviv-area/fhvn5ll9",
      renewal: "none",
      tags: [],
      firstSeen: "2026-09-11"
    },
    {
      id: "rehovot-mlbg9f2h",
      address: "מילצ'ן",
      city: "רחובות",
      neighborhood: "מיליצ'ן",
      price: 1750000,
      rooms: 3,
      sqm: 75,
      floor: 1,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/center-and-sharon/mlbg9f2h",
      renewal: "verified",
      renewalNote: "רחוב מילצ'ן - כל הרחוב בפינוי-בינוי מאושר",
      tags: [
        "בלעדי"
      ],
      firstSeen: "2026-09-11"
    },
    {
      id: "rehovot-8fgfwqax",
      address: "חיים אליעזר מילצ'ן 10",
      city: "רחובות",
      neighborhood: "מיליצ'ן",
      price: 1800000,
      rooms: 3,
      sqm: 67,
      floor: 4,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/center-and-sharon/8fgfwqax",
      renewal: "verified",
      renewalNote: "רחוב מילצ'ן - כל הרחוב בפינוי-בינוי מאושר",
      tags: [],
      firstSeen: "2026-09-11"
    },
    {
      id: "rehovot-684atc1y",
      address: "חיים אליעזר מילצ'ן",
      city: "רחובות",
      neighborhood: "מיליצ'ן",
      price: 1930000,
      rooms: 3,
      sqm: 72,
      floor: 3,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/center-and-sharon/684atc1y",
      renewal: "verified",
      renewalNote: "רחוב מילצ'ן - כל הרחוב בפינוי-בינוי מאושר; חורג מעט מתקציב היעד (1.9M)",
      tags: [
        "בלעדי"
      ],
      firstSeen: "2026-09-11"
    },
    {
      id: "kfar-saba-gkpgx7s3",
      address: "ויצמן",
      city: "כפר סבא",
      neighborhood: "מרכז",
      price: 1050000,
      rooms: 2,
      sqm: 60,
      floor: 2,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/center-and-sharon/gkpgx7s3",
      renewal: "none",
      tags: [
        "יחידת דיור"
      ],
      firstSeen: "2026-09-11"
    },
    {
      id: "bat-yam-fb1041246608827612",
      address: "דירה",
      city: "בת ים",
      neighborhood: "—",
      price: 560000,
      rooms: 2,
      sqm: null,
      floor: null,
      source: "פייסבוק",
      url: "https://www.facebook.com/marketplace/item/1041246608827612/",
      renewal: "none",
      tags: [],
      note: "חדר שינה אחד",
      firstSeen: "2026-09-11"
    },
    {
      id: "rehovot-r2qh8n19",
      address: "הרב דוד נדב",
      city: "רחובות",
      neighborhood: "קרית משה",
      price: 1425000,
      rooms: 3,
      sqm: 65,
      floor: 4,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/center-and-sharon/r2qh8n19",
      renewal: "none",
      renewalNote: "נבדק מול moch.maps.arcgis.com ב-17.9 — אין שום מתחם מוכרז באזור. טענת המוכר על הוותמ\"ל לא מגובה במפה הרשמית.",
      tags: [
        "קומה אחרונה"
      ],
      note: "אביאל ביקר בשטח (16.9) והתרשם ששלב ראשוני מאוד אם בכלל — תואם לבדיקת המפה: אין תכנית רשומה, לכל היותר שיחות לא רשמיות.",
      firstSeen: "2026-09-12"
    },
    {
      id: "by-vk19ptz1",
      address: "הרצל",
      city: "בת ים",
      neighborhood: "הגבול רוטשילד",
      price: 1330000,
      rooms: 2,
      sqm: 57,
      floor: 1,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/tel-aviv-area/vk19ptz1",
      renewal: "potential",
      renewalNote: "הגבול-רוטשילד — משכונות ההתחדשות החמות בבת ים.",
      tags: [],
      firstSeen: "2026-09-12"
    },
    {
      id: "by-brx20a5v",
      address: "רימון",
      city: "בת ים",
      neighborhood: "לב העיר",
      price: 1410000,
      rooms: 3,
      sqm: 66,
      floor: 2,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/tel-aviv-area/brx20a5v",
      renewal: "none",
      tags: [],
      firstSeen: "2026-09-12"
    },
    {
      id: "by-f7xhl1xc",
      address: "ארלוזורוב 79",
      city: "בת ים",
      neighborhood: "עצמאות יוספטל",
      price: 1450000,
      rooms: 2,
      sqm: 52,
      floor: 2,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/tel-aviv-area/f7xhl1xc",
      renewal: "none",
      tags: [],
      firstSeen: "2026-09-12"
    },
    {
      id: "holon-mdln-hugoarnest-16",
      address: "הוגו ארנסט 16",
      city: "חולון",
      neighborhood: "שיכון ותיקים",
      price: 385000,
      rooms: 4.5,
      sqm: 54,
      floor: 0,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/otirh61Mkfh",
      renewal: "none",
      tags: [
        "בית פרטי"
      ],
      note: "בית פרטי במחיר נמוך מאוד — ייתכן חלק מנכס/מכירה חלקית, לבדוק לפני התרגשות",
      firstSeen: "2026-09-12"
    },
    {
      id: "rishon-heil-hraglim",
      address: "חיל הרגלים",
      city: "ראשון לציון",
      neighborhood: "—",
      price: 419000,
      rooms: 4,
      sqm: 190,
      floor: 7,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/center-and-sharon/f2w3cz3z",
      renewal: "none",
      tags: [
        "פנטהאוז",
        "מחיר חשוד - לבדוק"
      ],
      note: "פנטהאוז 190 מ״ר במחיר נמוך באופן חריג — לבדוק אם תקין",
      hot: true,
      firstSeen: "2026-09-12"
    },
    {
      id: "rishon-ramat-eliyahu-45",
      address: "רמת אליהו",
      city: "ראשון לציון",
      neighborhood: "רמת אליהו",
      price: 1490000,
      rooms: 2.5,
      sqm: 45,
      floor: 2,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/center-and-sharon/1nmysmla",
      renewal: "none",
      tags: [
        "עלה ב-100,000 ₪"
      ],
      hot: true,
      firstSeen: "2026-09-12"
    },
    {
      id: "gs-u9tpikfc",
      address: "ז'בוטינסקי 50",
      city: "גבעת שמואל",
      neighborhood: "רמת אילן",
      price: 1299000,
      rooms: 2,
      sqm: 40,
      floor: 3,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/center-and-sharon/u9tpikfc",
      renewal: "none",
      tags: [
        "ירד ב-16,000 ₪"
      ],
      note: "אותו רחוב כמו gs-r9ymuyl8 / gs-ut5ee4no / gs-6czy8ll5 — כמה מודעות בבניין ז'בוטינסקי 50.",
      firstSeen: "2026-09-14"
    },
    {
      id: "by-fb-2259808151452180",
      address: "בת ים (לא צוינה כתובת)",
      city: "בת ים",
      neighborhood: "—",
      price: 1070000,
      rooms: null,
      sqm: null,
      floor: null,
      source: "פייסבוק",
      url: "https://www.facebook.com/marketplace/item/2259808151452180/",
      renewal: "none",
      tags: [
        "בלעדית"
      ],
      note: "פורסמה כ\"למכירה בבלעדיות\" בלי פרטי חדרים/מ\"ר/כתובת — לברר מול המוכר.",
      firstSeen: "2026-09-14"
    },
    {
      id: "rlz-y2-e0u8nyuh",
      address: "שדרות זלמן שניאור",
      city: "ראשון לציון",
      neighborhood: "רמת אליהו",
      price: 1430000,
      rooms: 2,
      sqm: 50,
      floor: 2,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/center-and-sharon/e0u8nyuh",
      renewal: "none",
      tags: [],
      firstSeen: "2026-09-20"
    },
    {
      id: "holon-y2-62m6zqu6",
      address: "הלוחמים",
      city: "חולון",
      neighborhood: "גרין ועם",
      price: 1450000,
      rooms: 3,
      sqm: 64,
      floor: 2,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/tel-aviv-area/62m6zqu6",
      renewal: "none",
      tags: [],
      firstSeen: "2026-09-20"
    },
    {
      id: "holon-y2-gdbu5i6z",
      address: "אילת 20",
      city: "חולון",
      neighborhood: "נאות רחל",
      price: 1440000,
      rooms: 3,
      sqm: 70,
      floor: 3,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/tel-aviv-area/gdbu5i6z",
      renewal: "none",
      tags: [],
      firstSeen: "2026-09-20",
      note: "מופיעה גם במדלן: VTzIfuS9fzc (שם 4 חד׳, 81 מ\"ר)"
    },
    {
      id: "bb-y2-b24m9cco",
      address: "הרב יצחק שמידמן",
      city: "בני ברק",
      neighborhood: "הר שלום",
      price: 1350000,
      rooms: 3,
      sqm: 65,
      floor: 1,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/center-and-sharon/b24m9cco",
      renewal: "none",
      tags: [
        "ירד ב-40,000 ₪"
      ],
      firstSeen: "2026-09-20"
    },
    {
      id: "by-y2-blmdh4e4",
      address: "בלפור",
      city: "בת ים",
      neighborhood: "דרום מערב ותיק",
      price: 1420000,
      rooms: 2,
      sqm: 55,
      floor: 1,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/tel-aviv-area/blmdh4e4",
      renewal: "none",
      tags: [],
      firstSeen: "2026-09-20"
    },
    {
      id: "by-y2-i3y6yrwi",
      address: "הנביאים",
      city: "בת ים",
      neighborhood: "הנביאים",
      price: 1370000,
      rooms: 3,
      sqm: 65,
      floor: 2,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/tel-aviv-area/i3y6yrwi",
      renewal: "none",
      tags: [],
      firstSeen: "2026-09-20"
    },
    {
      id: "holon-y2-t7xgfxld",
      address: "שדרות דב הוז",
      city: "חולון",
      neighborhood: "תל גיבורים",
      price: 1430000,
      rooms: 2,
      sqm: 40,
      floor: 0,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/tel-aviv-area/t7xgfxld",
      renewal: "none",
      tags: [
        "קומת קרקע"
      ],
      hot: false,
      firstSeen: "2026-09-28"
    },
    {
      id: "holon-y2-fvo7t0ku",
      address: "קלישר",
      city: "חולון",
      neighborhood: "אגרובנק",
      price: 1390000,
      rooms: 2.5,
      sqm: 44,
      floor: 0,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/tel-aviv-area/fvo7t0ku",
      renewal: "none",
      tags: [
        "קומת קרקע"
      ],
      note: "כנראה אותה דירה במדלן: 3AJyYy4korZ (שם רשום פנטהאוז 122 מ\"ר, ק7 — נתונים סותרים, לברר)",
      hot: false,
      firstSeen: "2026-09-28"
    },
    {
      id: "by-y2-vq9bm0a3",
      address: "דרך בן גוריון",
      city: "בת ים",
      neighborhood: "דרום חדש, פארק הים",
      price: 1250000,
      rooms: 2,
      sqm: 42,
      floor: 8,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/tel-aviv-area/vq9bm0a3",
      renewal: "none",
      tags: [
        "קומה גבוהה"
      ],
      hot: false,
      firstSeen: "2026-09-28"
    },
    {
      id: "by-y2-fyq8s4lc",
      address: "דרך בן גוריון",
      city: "בת ים",
      neighborhood: "דרום חדש, פארק הים",
      price: 1250000,
      rooms: 2,
      sqm: 38,
      floor: 9,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/tel-aviv-area/fyq8s4lc",
      renewal: "none",
      tags: [
        "קומה גבוהה"
      ],
      hot: false,
      firstSeen: "2026-09-28"
    },
    {
      id: "by-y2-qiqfxcsm",
      address: "בת ים (רחוב לא צוין)",
      city: "בת ים",
      neighborhood: "—",
      price: 1440000,
      rooms: 2,
      sqm: 60,
      floor: 1,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/tel-aviv-area/qiqfxcsm",
      renewal: "none",
      tags: [],
      hot: false,
      firstSeen: "2026-09-28"
    },
    {
      id: "by-y2-ouy2wfeq",
      address: "ההגנה",
      city: "בת ים",
      neighborhood: "לב העיר",
      price: 1450000,
      rooms: 2,
      sqm: 54,
      floor: 1,
      source: "יד2",
      url: "https://www.yad2.co.il/realestate/item/tel-aviv-area/ouy2wfeq",
      renewal: "none",
      tags: [],
      note: "כנראה אותה דירה במדלן: doIi5oLW0PB — ההגנה 30, בית וגן, 60 מ\"ר, ק2, 1,450,000 ₪",
      hot: false,
      firstSeen: "2026-09-28"
    },
    {
      id: "holon-mdln-aNkDIkLhJ3s",
      address: "זלמן ארן 29",
      city: "חולון",
      neighborhood: "נאות רחל",
      price: 1260000,
      rooms: 2,
      sqm: 48,
      floor: 1,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/aNkDIkLhJ3s",
      renewal: "none",
      tags: [],
      note: "דומה מאוד למודעה שנמחקה על זלמן ארן 27 (4z0DDfWEwzM, 1,270,000) — אולי אותה דירה שפורסמה מחדש",
      hot: false,
      firstSeen: "2026-09-28"
    },
    {
      id: "holon-mdln-dkyi2rAQosC",
      address: "דב הוז",
      city: "חולון",
      neighborhood: "תל גיבורים",
      price: 1430000,
      rooms: 3,
      sqm: 67,
      floor: 4,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/dkyi2rAQosC",
      renewal: "none",
      tags: [
        "3 חדרים"
      ],
      hot: true,
      firstSeen: "2026-09-28"
    },
    {
      id: "holon-fb-4109150009392444",
      address: "חנקין",
      city: "חולון",
      neighborhood: "רסקו א",
      price: 1260000,
      rooms: 2,
      sqm: 48,
      floor: 2,
      source: "פייסבוק",
      url: "https://www.facebook.com/marketplace/item/4109150009392444/",
      renewal: "none",
      tags: [
        "משופצת"
      ],
      note: "נראה כמו חנקין 55 שהייתה במדלן (LHs2dWdcOfy, 1,240,000) — שם המודעה נמחקה, בפייסבוק עדיין חיה",
      hot: false,
      firstSeen: "2026-09-28"
    },
    {
      id: "by-mdln-fizxhq6drkg",
      address: "מרכז העיר (בלי רחוב במודעה)",
      city: "בת ים",
      neighborhood: "מרכז העיר",
      price: 1430000,
      rooms: 2.5,
      sqm: 49,
      floor: null,
      source: "מדלן",
      url: "https://www.madlan.co.il/listings/FIzxHQ6DrKG",
      renewal: "none",
      tags: [
        "2.5 חדרים"
      ],
      hot: false,
      firstSeen: "2026-09-29"
    }
  ]
};
